version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
      - image: circleci/postgres:9.6-alpine-ram
        # environment:
        #   TEST_DATABASE_RUL: postgressql://root@localhost/circle_test
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: |
            python3 -m virtualenv venv
            source venv/bin/activate
            pip install -r requirements.txt
            python3 ./manage.py test api

workflows:
  sample:
    jobs:
      - build-and-test
